### ISSUE TITLE
Build a notebook that reformats data into JSON

### ISSUE THREAD

**Issue by Neri-hV** [alfredodeza/mapping-data#3]
I try to do the first exercise for Scripting with python and sql course of Coursera. 
You ask us :
_Use a distinct field to retrieve data, like:
_Type_ of wine (red or white)
_Wine_ score range or baseline (e.g. between 90 and 92 points) (How to do this?)
_Region_
_Capture_ every row that matches your condition, and after processing, save everything to a formatted new JSON file_

But  in the videos and laboratorios only say how to open the csv file using panda. 
However, I try to do this following the steps from serializing Json notebook  but I didn't have success wiith it. 
You could see what I did in the homework file
https://github.com/Neri-hV/mapping-data/blob/main/homework.ipynb

**Comment by awanhassan** [comment]
I also tried it many times but unable to load my dataset on jupyter notebook. Its throwing an error "file is not present". I have checked many times but it is doing the same issue everytime

**Comment by alfredodeza** [comment]
You both bring up a good point. I'll update this repository and the examples to make sure you can use the data structures that you were learning for this week and apply them. Sorry you had to run into trouble! And a huge thanks for bringing this up

**Comment by alfredodeza** [comment]
I've added extra instructions and guidance to the repository README as well as the Coursera instructions. Additionally, I've created a notebook that you can reuse that has pre-written code that has loaded the example data and has sample on how to work with the data. 

Hopefully this helps you both out. Thanks again for reporting this! And please feel free to re-open this or other issues if you need anything else
